services:
  - type: web
    name: google-maps-scraper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && playwright install --with-deps"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PROXY
        sync: false  # Optional, add manually if using proxies
